version: '3.8'

services:
  rsvp-web:
    image: korexdotcf/openrsvp-web:latest
    container_name: rsvp-web-local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - rsvp_local_network

networks:
  rsvp_local_network:
    driver: bridge
